version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: goldengains-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: goldengains
      POSTGRES_PASSWORD: goldengains
      POSTGRES_DB: goldengains
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data: